### PR TITLE
fix: Make platform host logic work for all quip sites

### LINKED ISSUE #171: quip-cli login site mismatch
Issues with various login commands

`$ qla login`
Errors on browser because the initial request goes to `https://quip.com` and I am not properly redirected to `https://corp.quip.com`. The google auth fails to authorize me. 

This is resolved by setting the `site` flag

`$ qla login --site=corp.quip.com` 
Errors because the site argument is used to derive the platform endpoint as `platform-${site}`. 
The request (`https://platform-corp.quip.com`) results in a not found error on the terminal.

### PR DESCRIPTION
**Pull request by jesseditson**
Fixes https://github.com/quip/quip-apps/issues/171

### CODE REVIEW

File: packages/quip-cli/src/lib/cli-api.ts [hunk 1]
```diff
@@ -121,9 +121,18 @@ const cliAPI = async (configPath: string, site: string) => {
...
+    if (site === "staging.quip.com") {
+        return "platform-staging.quip.com";
+    }
+    if (siteParts.length > 2) {
+        if (siteParts.slice(-2).join(".") === "onquip.com") {
+            return `platform.${siteParts.slice(-3).join(".")}`;
+        }
+        return `platform.${siteParts.slice(-2).join(".")}`;
+    }
+    return `platform.${site}`;
```
Comment (jesseditson) [inline packages/quip-cli/src/lib/cli-api.ts:135]: This logic is derived from https://github.com/quip/quip/blob/675ac6e717fe32e93388a60eb5054dd32e05b185/lib/vpc_migration/util.py#L166

**Review by gaspar09 — APPROVED** [review]
Nice solution
